_target_: workspace.src.filters.filter_images.filter_glasses_image.FilterGlassesImage

# defaults:
#   - model: filter_resnet.yaml
#   - transform: filter_transform.yaml
#   - _self_

model: ${model}

transform: ${transform}

image_folder: ${paths.input_image_dir}

filter_name: 'eye_glasses.png'

device: 'cpu'